

name: Storybook CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run build-storybook --if-present
      - run: npm publish --if-present
      # config
      - run: git config user.email "adedotster@gmail.com"
      - run: git config user.name "Diorla"
      # update static file
      - run: git add storybook-static
      - run: git commit -m "`r format(Sys.time(), '%d %B, %Y')`"
      - run: git push origin main